### ISSUE TITLE
Noetic ‘python’: No such file or directory

### ISSUE THREAD

**Issue by simonbogh** [ros-visualization/rqt_robot_steering#10]
When running rosrun `rosrun rqt_robot_steering rqt_robot_steering` version 0.5.11 on ROS Noetic Ubuntu 20.04 I get the following error:

    /usr/bin/env: ‘python’: No such file or directory

**Comment by dirk-thomas** [comment]
This was fixed in #9 but hasn't been released since then. You can apply the patch locally until a new release is available. (I will kick off a new release soon.)

**Comment by simonbogh** [comment]
Thank you

**Comment by simonbogh** [comment]
I still do not see a deb release of 0.5.12 for Noetic, it is still at 0.5.11 when installing from binary. Can you push a binary release?
